from enum import Enum

class Decision(str, Enum):
    APPROVE = "APPROVE"
    WAIT = "WAIT"
    REJECT = "REJECT"

class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NONE = "NONE"

class Trend(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    TRANSITION = "TRANSITION"
    UNINITIALIZED = "UNINITIALIZED"

class SupervisorMode(str, Enum):
    STARTUP = "STARTUP"
    STRUCTURE_MONITORING = "STRUCTURE_MONITORING"
    OPPORTUNITY_MONITORING = "OPPORTUNITY_MONITORING"
    CANDIDATE_REVIEW = "CANDIDATE_REVIEW"
    EXECUTION_PENDING = "EXECUTION_PENDING"
    TRADE_FOCUS = "TRADE_FOCUS"
    POST_TRADE_UPDATE = "POST_TRADE_UPDATE"
    DAILY_LOCKED = "DAILY_LOCKED"
    WEEKEND_LOCKED = "WEEKEND_LOCKED"
    SAFE_MODE = "SAFE_MODE"

class EvidenceRelationship(str, Enum):
    SAME_EVENT_MULTIPLE_DESCRIPTIONS = "SAME_EVENT_MULTIPLE_DESCRIPTIONS"
    INDEPENDENT_CONFIRMATION = "INDEPENDENT_CONFIRMATION"
    SEQUENTIAL_CONFIRMATION = "SEQUENTIAL_CONFIRMATION"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
